### ISSUE TITLE
Implement buttons to add product

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#12]
> [!IMPORTANT]
> Read issue #2 first

Edit the following buttons (only those with the `disabled` attribute)

| Normal | With imagen |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/4dfbb48b-db1e-4369-b740-19541819f1fe) | ![image](https://github.com/user-attachments/assets/f40bb0a0-ef00-4258-8194-d9a9ac6d6aed) |

https://github.com/despensa-app/despensa-web/blob/fe6d987ba861cb85a6b18034b7553e699441f982/src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.html#L35-L65

https://github.com/despensa-app/despensa-web/blob/fe6d987ba861cb85a6b18034b7553e699441f982/src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.html#L103-L132

and add the following event:

```typescript
(click)="addProduct(product, 1)"
``` 

Remove the `disabled` attribute.
Increment the numerical value for each button, up to the maximum value which is 4.

Add the following code at the end of the class [`AddProductsShoppingListComponent`](https://github.com/despensa-app/despensa-web/blob/fe6d987ba861cb85a6b18034b7553e699441f982/src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.ts):

```typescript
addProduct(product: ProductInstantSearch, unitsPerProduct: number) {
  const request: SaveShoppingListProductReq = {
    productId: product.id,
    shoppingListId: this.idShoppingList,
    unitsPerProduct: unitsPerProduct,
    unitTypeId: this.findAllUnityTypesRes().content[0].id
  };

  this.showDialogSelectProductEvent(product);
  this.addProductsSubmit(request);
}
```

**Comment by meetbhalodi11** [comment]
@nmarulo I would like to work on this one

**Comment by JinnJarBurger** [comment]
Hello @nmarulo, could you please assign this to me? Thanks!

**Comment by nmarulo** [comment]
@meetbhalodi11 It's all yours 👍
