### ISSUE TITLE
Search deepsource issues

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#14]
> [!IMPORTANT]
> Read issue #2 first

In deepsource there are currently 46 issues:

https://app.deepsource.com/gh/despensa-app/despensa-web/issues/?category=all&page=1

You can create an issue indicating which ones you want to deepsource.

I have looked at some issues and most of them are to correct a single line, in that case the issue you create in github must group several issues to correct at least 5 lines, no more and no less. If the issue is more complex, you don't need to group several issues.

You don't need to comment anything here, unless you have any doubt. Create the issue, I will review it and give you the go ahead so you can start. 

---

<details><summary>Created issues</summary>

- [x] #16

</details>

**Comment by Srijan25** [comment]
Detected empty functions JS-0321 can i solve this issue

**Comment by nmarulo** [comment]
@Srijan25 If you create the issue, I will assign it to you.
