### ISSUE TITLE
Detected empty functions JS-0321

### ISSUE THREAD

**Issue by Srijan25** [despensa-app/despensa-web#16]
Unexpected empty method 'click'
[src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.ts](https://github.com/despensa-app/despensa-web/blob/master/src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.ts#L107-L108)  

[src/app/layout/navbar/navbar.component.ts](https://github.com/despensa-app/despensa-web/blob/master/src/app/layout/navbar/navbar.component.ts#L22-L23)

 src/app/services/layout/sidebar.service.ts

can you assign me under hacktoberfest

**Comment by nmarulo** [comment]
@Srijan25 It's all yours 👍
