### ISSUE TITLE
📣 Hacktoberfest 2024

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#2]
> [!IMPORTANT]
> - The issues that I create for the hacktoberfest will be closed until the 1st of October.
> - The issues noted with the `hacktoberfest` label, are for event and will be enabled on October 1st. **They cannot be resolved before that date.**
> - Please do not create Pull Requests from issues noted with the `hacktoberfest` label that are not assigned to you.
> - When you are assigned an issue, **you must confirm it by commenting on the issue within 24 hours after the assignment**, this is just so I can know if you have heard or not, if I do not receive a reply I will assign it to someone else.

Hello everyone 👋, I'm Nicolás, Java programmer and I'm working on this project as a hobby. I've been learning and practicing Spring-boot and Angular, and I'm applying little by little, everything I've learned, in this project.

It doesn't matter if you are just starting or have been working with these two technologies for a short time, I will try to help those who want to make their first contributions on github, creating some simple issues.

Find all the issues for the hacktoberfest [here](https://github.com/despensa-app/despensa-web/milestone/1).

Each issue noted with `hacktoberfest` must be completed within a week and **you can only do one per week**, this is to give more participants a chance. If you are interested in resolving any issues or have questions, please comment in the corresponding issue.

Each issue will also have a label indicating its level of difficulty:

- `Easy`: I practically give you the solution in the issue, you only have to follow the indications. These issues are focused to developers who want to make their first contributions, so if several people ask for the same issue I will decide who to assign it to regardless of the order of arrival.
- `Medium`: I explain you what to do and I may give part of the solution.
- `Complex`: I explain you what to do, but it will have a part of research on your own.

You can also suggest issues. These do not have a maximum time to be completed and you can create as many as you see fit.

Thank you very much 😁.

> [!NOTE]
>Please let me know if you can't complete the issue. These things happen, no problem 👍.

**Comment by Abhrajitdas02** [comment]
assign it to me @nmarulo

**Comment by nmarulo** [comment]
@Abhrajitdas02 This issue is for information and clarification only. On October 1st the issues created for the event will be opened.
