### ISSUE TITLE
fixing Deepsource issues 

### ISSUE THREAD

**Issue by weshaan** [despensa-app/despensa-web#20]
This issue continues to #14 

issues selected to patch:

1. Found explicit type declarations JS-0331 (2 lines)
2. Detected empty functions JS-0321 (3 lines)

**Comment by nmarulo** [comment]
@weshaan JS-0321 is in progress, please select another one.

**Comment by weshaan** [comment]
> @weshaan JS-0321 is in progress, please select another one.

okay

**Comment by nmarulo** [comment]
I closed this issue, but if you still want to do it, I can open the issue again, it is not necessary to create another one, you would only have to modify the issue and change JS-0321 for another one.

**Comment by weshaan** [comment]
okay, can i do JS-0105(3 lines) and JS-0331(2 lines)?

**Comment by nmarulo** [comment]
of source
