### ISSUE TITLE
Add Lazy loading in the routes

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#3]
> [!IMPORTANT]
> Read issue #2 first

Update the file [app.router.ts](https://github.com/despensa-app/despensa-web/blob/ed142000efab1210e38f7999b9028d96032122f8/src/app/app.routes.ts) to change the `component` fields of the routes to `loadComponent`.

Example:

```javascript
{
  path: 'shopping-list/:id/add-products',
  loadComponent: () => import('./modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component').then(m => m.AddProductsShoppingListComponent)
}
```

Reference: [Routing and lazy-loading](https://v17.angular.io/guide/standalone-components#routing-and-lazy-loading)

**Comment by Eduguimar** [comment]
Hello @nmarulo , can you assign this issue to me, please? I would like to contribute.

**Comment by Ashu1823** [comment]
Hi..
Intrested to work in this issue.
Can you please assign it to me?

**Comment by nmarulo** [comment]
@Ashu1823  It's all yours 👍

**Comment by Ashu1823** [comment]
@nmarulo thank you.

**Comment by smzoha** [comment]
Hey @nmarulo. If the issue goes stale eventually, can I please try my hand at it?

**Comment by Ashu1823** [comment]
Hi @nmarulo. Can we have a connect.. I need to test the changes but getting some error from the service files.

**Comment by nmarulo** [comment]
> Hi @nmarulo. Can we have a connect.. I need to test the changes but getting some error from the service files.

@Ashu1823 What problem is the application showing you? 

In case you need to run the API, you can follow [this demo video](https://github.com/despensa-app/despensa-rest-api/discussions/29)

**Comment by Ashu1823** [comment]
@nmarulo Do I need to run it in local. we don't have any server deployed the BE code?

**Comment by nmarulo** [comment]
> @nmarulo Do I need to run it in local. we don't have any server deployed the BE code?

@Ashu1823 The currently deployed API, for the demo, only works within the same domain to avoid excessive resource usage, since it is a free server. You cannot consume it locally, for that you have to start a local server.

And currently it is not mandatory to have the API running locally. You can run the repository and the application should start without problems, it just won't work when interacting with the API.

In case you have docker, this repository has a `compose.yaml` file, I comment it in case you use docker.

**Comment by Ashu1823** [comment]
Hi @nmarulo Modified the route file and raised the PR.
