### ISSUE TITLE
Add pr-size-labeler for Github Action

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#5]
> [!IMPORTANT]
> Read issue #2 first

I've seen how this Github Action works and would like to add it to my repository. If anyone wants to try to add it, go ahead.

This is the repository with the documentation: https://github.com/CodelyTV/pr-size-labeler

Thank you very much.

**Comment by smzoha** [comment]
Hi @nmarulo. Can I please take a shot at this? 
I understand if I'm not allowed to work on two issues in a row (so that others can work on this).

**Comment by nmarulo** [comment]
@smzoha It's all yours 👍

> Hi @nmarulo. Can I please take a shot at this? I understand if I'm not allowed to work on two issues in a row (so that others can work on this).

This condition only applies within the same repository.

**Comment by smzoha** [comment]
Thank you once again! I'll give this a shot tomorrow.
