### ISSUE TITLE
Create docker compose file

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-web#8]
> [!IMPORTANT]
> Read issue #2 first

Create the `compose.yaml` file, to work with the [rest-api 0.0.1-test image](https://hub.docker.com/r/nmarulo/despensa-app) that I uploaded for testing.

Reference: Project git [despensa-rest-api.yaml](https://github.com/despensa-app/despensa-rest-api/blob/04819258d0a530ed9a0b0f35831d0d2aa2a3c9a6/compose.despensa-rest-api.yaml)

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by nmarulo** [comment]
@ArinNigam it's all yours 👍

**Comment by nmarulo** [comment]
As stated in issue #2

> When you are assigned an issue, you must confirm it by commenting on the issue within 24 hours after the assignment, this is just so I can know if you have heard or not, if I do not receive a reply I will assign it to someone else.

**Comment by ArinNigam** [comment]
I was working with the issue. I just ran with some errors so wasn't able to make a PR.

**Comment by nmarulo** [comment]
@ArinNigam Ok, it assigns it back to you. What I am saying is that I need you to confirm that you know that I assigned the issue to you. It was just that, I didn't mean that you had to do the PR now, you have time.
